"""push_info

Revision ID: 176daa0a163b
Revises: 3437fd525d72
Create Date: 2023-06-14 10:48:16.107880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176daa0a163b'
down_revision = '3437fd525d72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.add_column('games', sa.Column('push_info_0', sa.String(), nullable=True))
    op.add_column('games', sa.Column('push_info_1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'push_info_1')
    op.drop_column('games', 'push_info_0')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
