"""INIT

Revision ID: 5134a8351181
Revises: 
Create Date: 2023-06-13 10:12:13.449160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5134a8351181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('game_state', 'turn',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_state', 'win_0',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_state', 'win_1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_state', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pieces_table', 'piece_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pieces_table', 'pos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pieces_table', 'player',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pieces_table', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pieces_table', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pieces_table', 'player',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pieces_table', 'pos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pieces_table', 'piece_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_state', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_state', 'win_1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_state', 'win_0',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_state', 'turn',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('qqch',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('user')
    # ### end Alembic commands ###
